
services:
  Sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ShopDB
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Sh0pAcces
      MSSQL_PID: Express
    ports:
      - 1433:1433
    volumes:
       - ./data:/var/opt/mssql/data
       - ./log:/var/opt/mssql/log